Improved guest template creation process

diff --git a/playbooks/kvm-guest-template.yml b/playbooks/kvm-guest-template.yml
--- a/playbooks/kvm-guest-template.yml
+++ b/playbooks/kvm-guest-template.yml
@@ -1,65 +1,72 @@
 ---
+# Create KVM Guest Template
 - hosts: localhost
   gather_facts: true
   become: yes
+  
   vars:
     guest_os: ubuntu2204
+   
   roles:
-  - role: create-kvm-guest
+  - role: kvm-guest-template
+
+
+# Configure KVM Guest Template
+# - vconsole
 
 - hosts: new_kvm_guest
-  gather_facts: false
+  gather_facts: true
   become: true
 
   vars:
     guest_os: ubuntu2204
+    host_reboot: false
   
   pre_tasks:
-  - ansible.builtin.assert:
-      that:
-        - lookup('env', 'kvm_guest_user') != ""
-        - lookup('env', 'kvm_guest_password') != ""
-      fail_msg:
-        - "kvm_guest_user and kvm_guest_password env var must be exported to authenticate new create KVM VM"
-        - "export kvm_guest_user=xxx"
-        - "export kvm_guest_password=xxx"
-  
-  - ansible.builtin.setup:
-  
-  - name: Include vars from {{custom_guest_input}}
+  - name: Include vars from file provided in custom_guest_input extra var
     ansible.builtin.include_vars:
       file: "{{custom_guest_input}}"
     when: custom_guest_input is defined
 
-  - name: Include default vars from create-kvm-guest
+  - name: Include default vars from kvm-guest-template
     ansible.builtin.include_vars:
-      file: create-kvm-guest/defaults/main.yml
+      file: "{{lookup('env','PWD')}}/kvm-guest-template/defaults/main.yml"
     when: custom_guest_input is not defined
 
-  tasks:
-  - name: Include tweak-kvm-guest role ro setup vconsole
-    ansible.builtin.include_role:
-      name: tweak-kvm-guest
-      tasks_from: vconsole.yml
-
-  - name: Include os-tuing role to set static IP in VM
+  tasks:    
+  - name: Include os-tuning role to setup vconsole, disable ipv6 and disable biosdevname
     ansible.builtin.include_role:
       name: os-tuning
-      tasks_from: static-ip.yml
+      tasks_from: main.yml
 
   - name: Reboot host 
     ansible.builtin.shell: |
-      virsh reboot {{image_type[guest_os]['template']['name']}}
+      virsh shutdown {{image_type[guest_os]['template']['name']}}
+      [ $? != 0 ] && echo "Failed to shutdown VM" && exit 1
       sleep 10
-      if ! virsh domstate  {{image_type[guest_os]['template']['name']}}|egrep "running"; then
-        virsh start {{image_type[guest_os]['template']['name']}}
-      fi
+      virsh start {{image_type[guest_os]['template']['name']}}
+      sleep 30
+    args:
+      executable: /bin/bash
     delegate_to: localhost
+    when: host_reboot|bool
 
-  - ansible.builtin.pause:
-      echo: yes
-      prompt: "\nINFO: Machine is rebooting, wait for 2 mins"
-      minutes: 2
+  - name: Update ansible facts
+    ansible.builtin.setup:
+
+  - name: Include os-tuning role to set dhcp identifier
+    ansible.builtin.include_role:
+      name: os-tuning
+      tasks_from: dhcp-identifier.yml
+
+  - name: Reboot host 
+    ansible.builtin.shell: |
+      virsh shutdown {{image_type[guest_os]['template']['name']}}
+      [ $? != 0 ] && echo "Failed to shutdown VM" && exit 1
+      sleep 10
+      virsh start {{image_type[guest_os]['template']['name']}}
+      sleep 30
+    args:
+      executable: /bin/bash
     delegate_to: localhost
-
-  
+    when: host_reboot|bool
